name: SCALEX
description: |
  SCALEX is an integration and projection tool for atlas-level single-cell RNA-seq and ATAC-seq data.
project_home: https://github.com/jsxlei/SCALEX
documentation_home: https://scalex.readthedocs.io/en/latest/?badge=stable
publications:
  - 10.1038/s41467-022-33758-z
install:
  pypi: SCALEX
tags:
  - scRNA-seq
  - integration
  - projection
  - scATAC-seq
license: MIT
version: v1.0.3
authors:
  - Lei Xiong
test_command: pip install ".[test]" && pytest
